### ISSUE TITLE
Inconsistent and confusing errors returned upon cancel

### ISSUE THREAD

**Issue by mjgarton** [uw-labs/substrate#126] opened 2020-06-23 13:10 UTC
Depending upon which backend  is used, sometimes context cancellation will return nil and sometimes will return context.Canceled.

This should be consistent across backends, because currently workaround are needed to avoid callers getting into unwanted states.

To work around this currently, callers have to do more complex error checking than should be needed.

I propose that we make this consistent and when the passed in ctx is Done(), we return ctx.Err() in all cases.

**Comment by ggordan** [comment] 2020-06-23 13:41
This is great, I've got code for this locally as we've frequently encountered confusing problems while using `errgroup`, however I've found test runs to be inconsistent hence no PR.

**Comment by SpeedyCoder** [comment] 2020-06-23 13:42
I think all backends should be returning `nil` on context cancellation at the moment. There are possibly a few cases where deadline exceeded error is returned to the client, but that should be easy to fix. 

The contract at the moment should be that all backends return nil error only on context cancellation. Where do you guys see inconsistent behaviour?

**Comment by SpeedyCoder** [comment] 2020-06-23 13:52
From looking at the code I don't think `context.Cancelled` error should be surfaced anywhere except the synchronous sink adapter. If it is then it's a bug. I'm not necessarily against changing things to always return `ctx.Err()`, but that's a different conversation than fixing a bug.

**Comment by mjgarton** [comment] 2020-06-23 13:54
@ggordan I've got workaround in 2 apps now and keep hitting bugs because of this, so finally decided to do something about it!

**Comment by ggordan** [comment] 2020-06-23 13:57
@SpeedyCoder inconsistent after the changes in my local branch where I've attempted to return `ctx.Err()`. Not suggesting a problem in the current release of substrate, just that I've encountered a problem while making this change that I've not got around to fixing. 

So not a bug, but in my opinion the correct behaviour would be to return `ctx.Err()` when the consumer is exiting on a `ctx.Done()` and let the user decide what to do with that.

**Comment by mjgarton** [comment] 2020-06-23 14:00
@SpeedyCoder I am primarily arguing for consistency here, regardless of which way we go.  My preference of returning the context error is that callers wanting that but sometimes actually being returned nil, has been the source of multiple (often subtle) bugs in my experience.  I've not yet seen a bug caused by expecting nil but getting ctx.Canceled, but if they do exist, I suspect they are more likely to be obvious and easily fixed.

**Comment by SpeedyCoder** [comment] 2020-06-23 14:26
I'm definitely 100% for consistency. I think you can only get cancelation error from the underlying libraries atm, but I've only skimmed through the code, so might have missed something. Not sure what is more idiomatic, but it's definitely easier letting the user decide what to do with context error. The only issue might be when we get a cancellation error, but the context that we passed in was not canceled...

So the change you are proposing is that a backend implementation should always return an error and it will be the error from the provided context on context cancellation. Might be worth writing some of this stuff down.

Note that most of the stuff is coded defensively using rungroup, so that if one part of a pipeline stops even without an error the rest will do as well and this might result in context cancellation error being returned even if the provided context wasn't cancelled. If there is such bug it would return `nil` error atm, what is equally wrong 😅

**Comment by mjgarton** [comment] 2020-06-23 14:48
I am actually less sure now, given that the tests (which don't pass currently on my PR) seem to enforce that nil is returned, at least in some of the cases.

But I am still sure they substrate is returning `nil` to me when I cancel the context, and that's a source of bugs because it's surpising.  Perhaps it's been like that for a long time, or even forever, but it's still a source of bugs.

So my PR may be wrong in its current form, but I still argue there is a design bug here.

**Comment by mjgarton** [comment] 2020-06-23 15:42
@SpeedyCoder I think your description of what I am proposing it correct.

If we agree this is worth pursuing, I'll complete this PR (i.e., do the same for the other backends and update the tests) and I'll also clarify the documentation to explain it a bit more.

**Comment by SpeedyCoder** [comment] 2020-06-23 15:50
Sounds good, if getting `nil` error is confusing users, then it seems like a good change 👍 

Might need to update `substrate-tools` and `proximo` as well once it gets merged...

**Comment by heedson** [comment] 2020-06-23 16:18
To throw my hat into the ring - I've always operated in situations like these as a "return everything" and let the user decide what to do. Depending on the deeper design decisions, I usually return the context errors and allow the user to have the choice whether to propagate or act upon it or just simply ignore it.

**Comment by mjgarton** [comment] 2020-06-23 16:43
Okay, it seems we all broadly agree, so I'll keep working on the PR and get it into a decent shape as soon as I have time.

**Comment by mjgarton** [comment] 2020-06-24 17:50
For the record, it was inaccurate of me to call the existing behaviour "inconsistent".  It was, however, confusing, not well documented and arguably non-idiomatic.  If has been changed in #127

**Closed** 2020-06-24 17:50 UTC
